#!/usr/bin/env python3
"""
Generate protobuf Python bindings for YoloVr tracker data
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path


def find_protoc():
    """Find the protoc compiler"""
    protoc_path = shutil.which('protoc')
    if protoc_path:
        return protoc_path
    
    # Common installation paths
    common_paths = [
        '/usr/local/bin/protoc',
        '/usr/bin/protoc',
        '/opt/homebrew/bin/protoc',  # macOS Homebrew
        'C:\\Program Files\\Google\\Protobuf\\bin\\protoc.exe',  # Windows
    ]
    
    for path in common_paths:
        if os.path.exists(path):
            return path
    
    return None


def main():
    """Generate protobuf bindings"""
    # Get script directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent
    proto_file = project_root / 'proto' / 'tracker_data.proto'
    output_dir = script_dir.parent / 'yolovr'
    
    print(f"Script directory: {script_dir}")
    print(f"Project root: {project_root}")
    print(f"Proto file: {proto_file}")
    print(f"Output directory: {output_dir}")
    
    # Check if proto file exists
    if not proto_file.exists():
        print(f"Error: Proto file not found at {proto_file}")
        return 1
    
    # Find protoc
    protoc = find_protoc()
    if not protoc:
        print("Error: protoc compiler not found!")
        print("Please install Protocol Buffers compiler:")
        print("  Ubuntu/Debian: sudo apt install protobuf-compiler")
        print("  Fedora/RHEL: sudo dnf install protobuf-compiler")
        print("  macOS: brew install protobuf")
        print("  Windows: Download from https://github.com/protocolbuffers/protobuf/releases")
        print("")
        print("Note: Only protoc (the compiler) is needed, not the Python protobuf package.")
        print("The Python bindings will be generated by protoc.")
        return 1
    
    print(f"Using protoc: {protoc}")    # Create output directory
    output_dir.mkdir(exist_ok=True)
    
    # Generate Python bindings
    cmd = [
        protoc,
        f'--proto_path={proto_file.parent}',
        f'--python_out={output_dir}',
        str(proto_file)
    ]
    
    print(f"Running: {' '.join(cmd)}")
    
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        print("✓ Protobuf Python bindings generated successfully!")
        
        # Check if the output file was created
        expected_output = output_dir / 'tracker_data_pb2.py'
        if expected_output.exists():
            print(f"✓ Generated: {expected_output}")
        else:
            print(f"Warning: Expected output file not found: {expected_output}")
            return 1
            
    except subprocess.CalledProcessError as e:
        print(f"Error running protoc: {e}")
        if e.stdout:
            print(f"stdout: {e.stdout}")
        if e.stderr:
            print(f"stderr: {e.stderr}")
        return 1
    
    print("\nProtobuf generation complete!")
    print("You can now import the generated bindings with:")
    print("  from yolovr import tracker_data_pb2")
    
    return 0


if __name__ == '__main__':
    sys.exit(main())